### PR TITLE
maindb v4

### PR DESCRIPTION
**Pull request by qianbin**
This PR upgrades maindb to v4. It greatly reduces the storage space occupied and significantly reduces the synchronization time.

* For MPT
    * The encoding and storage format of nodes are comprehensively improved, reducing the storage space used to store the state trie by 30%. Moreover, the speed of encoding and decoding nodes has been greatly improved.
    * Introducing the concept of *Version* to identify nodes, which simplifies the implementation code.
    * Optimize the trie interface to make it easier to maintain.
    * Remove leafbank stuff.
    * Improve generation-based node cache to reduce the pressure of GC.
    * Improve node storage key encoding.
* Optimize block indexing and storage format.

Check out commits for more detail.

### CODE REVIEW

**Review by claytonneal — CHANGES_REQUESTED** [review]
Please give more details of what testing is needed

**Comment by qianbin** [comment]
> Please give more details of what testing is needed

1. try sync with and without `-disable-pruner`, and record the time and disk space used.
2. test correctness of APIs

**Comment by daithihearn** [comment]
Hi @qianbin I was playing around with your changes and wanted to share some results about the sync performance.

image

**Comment by qianbin** [comment]
> Hi @qianbin I was playing around with your changes and wanted to share some results about the sync performance.
> 
> image

That's good. How about turning on `-skip-logs`?

**Comment by daithihearn** [comment]
image

**Comment by darrenvechain** [comment]
Hey @qianbin could you update your branch with latest master? The CI won't pass until that happens

**Pull request closed without merging**
