### PR TITLE
ignore known tx in pending tx subscription

### PR DESCRIPTION
**Pull request by libotony**

### CODE REVIEW

**Comment by qianbin** [comment]
I think per-connection LRU is more reasonable, or let the client do the filtering.

**Comment by libotony** [comment]
Client filtering might not be a good idea, since duplicated tx happens a lot, caused by multiple peer-to-peer node broadcasting new tx.

As a hub for re-distributing events, it might be efficient to filter in place. Per-connection LRU is perfect at the design level, but it might cost more memories, do you consider it's affordable?



> I think per-connection LRU is more reasonable, or let the client do the filtering.

**Comment by qianbin** [comment]
> As a hub for re-distributing events, it might be efficient to filter in place. Per-connection LRU is perfect at the design level, but it might cost more memories, do you consider it affordable?

Sorry, I misunderstood the code.

A few minor changes are made within the last two commits.

**Comment by libotony** [comment]
> > As a hub for re-distributing events, it might be efficient to filter in place. Per-connection LRU is perfect at the design level, but it might cost more memories, do you consider it affordable?
> 
> Sorry, I misunderstood the code.
> 
> A few minor changes are made within the last two commits.

Changes LGTM, still needs your review, I can't review it due to I am the author.

**Review by qianbin — APPROVED** [review]

**Pull request merged**
