### PR TITLE
Rename best to latest

### PR DESCRIPTION
**Pull request by MakisChristou**
# Description
Renaming of block label best to latest.

Fixes [#91](https://github.com/vechain/protocol-board-repo/issues/91)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Test A
- [x] Test B

**Test Configuration**:
* Go Version:
* Hardware:
* Docker Version:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] New and existing E2E tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have not added any vulnerable dependencies to my code

### CODE REVIEW

**Review by darrenvechain — CHANGES_REQUESTED** [review]
This PR introduces a breaking change. As a best practice, it's crucial to ensure that existing endpoints remain backward compatible.

The discussion around naming conventions on blocks is still ongoing I believe.

**Comment by darrenvechain** [comment]
> heya, think the idea is to support latest and best! so if the user passed "latest" just map it to "best" also there is function "handleRevision" in accounts.go that also parses the revision, that needs updating too!

Something to watch out for around handleRevision is `finalized`. I think this field is currently only used in `/blocks` and not other domains

**Comment by MakisChristou** [comment]
> est practice, it's crucial t

So would that entail just modifying the `parseRevision` function to include latest as well? That seems to do the trick in practice. Both `best` and `latest` are work on the swagger API.

**Comment by claytonneal** [comment]
Is this PR dead now? Should it be closed? cheers

**Pull request closed without merging**
