### PR TITLE
chore: update contributing docs

### PR DESCRIPTION
**Pull request by darrenvechain**
# Description

Update contributing guidelines

# How Has This Been Tested?

git commit

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] New and existing E2E tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have not added any vulnerable dependencies to my code

### CODE REVIEW

**Comment by libotony** [comment]
A general question on the file, since it's a md file, do we need to manage the line length ourselves?

**Comment by darrenvechain** [comment]
> A general question on the file, since it's a md file, do we need to manage the line length ourselves?

How do you mean by manage the line length?

**Comment by libotony** [comment]
> > A general question on the file, since it's a md file, do we need to manage the line length ourselves?
> 
> How do you mean by manage the line length?

In the code, the line has human-made line breaks. For example:

``` test
1 6. Push your changes to your forked repository. **Note:** All commits must be signed with a GPG key. If you haven't already set up a GPG key, please refer to the
2   GitHub documentation
```

**Comment by darrenvechain** [comment]
> > > A general question on the file, since it's a md file, do we need to manage the line length ourselves?
> > 
> > 
> > How do you mean by manage the line length?
> 
> In the code, the line has human-made line breaks. For example:
> 
> ```
> 1 6. Push your changes to your forked repository. **Note:** All commits must be signed with a GPG key. If you haven't already set up a GPG key, please refer to the
> 2   GitHub documentation
> ```

Ah yes, this is auto formatting from JetBrains. I can manually remove these if it's preferred?

**Comment by libotony** [comment]
> > > > A general question on the file, since it's a md file, do we need to manage the line length ourselves?
> > > 
> > > 
> > > How do you mean by manage the line length?
> > 
> > 
> > In the code, the line has human-made line breaks. For example:
> > ```
> > 1 6. Push your changes to your forked repository. **Note:** All commits must be signed with a GPG key. If you haven't already set up a GPG key, please refer to the
> > 2   GitHub documentation
> > ```
> 
> Ah yes, this is auto formatting from JetBrains. I can manually remove these if it's preferred?

Can you do another format on top of this PR? I have noticed it via 

```
1    - **Note:**: Please refer to the [README](https://github.com/vechain/thor/blob/master/README.md) for information on
2      how to start the node and interact with the
3      API
```

**Comment by darrenvechain** [comment]
> > > > > A general question on the file, since it's a md file, do we need to manage the line length ourselves?
> > > > 
> > > > 
> > > > How do you mean by manage the line length?
> > > 
> > > 
> > > In the code, the line has human-made line breaks. For example:
> > > ```
> > > 1 6. Push your changes to your forked repository. **Note:** All commits must be signed with a GPG key. If you haven't already set up a GPG key, please refer to the
> > > 2   GitHub documentation
> > > ```
> > 
> > 
> > Ah yes, this is auto formatting from JetBrains. I can manually remove these if it's preferred?
> 
> Can you do another format on top of this PR? I have noticed it via
> 
> ```
> 1    - **Note:**: Please refer to the [README](https://github.com/vechain/thor/blob/master/README.md) for information on
> 2      how to start the node and interact with the
> 3      API
> ```

Yepp, I fixed formatting and pushed it latest commit

**Review by libotony — APPROVED** [review]

**Pull request merged**
