### PR TITLE
Add muxdb test to increase coverage

### PR DESCRIPTION
**Pull request by MakisChristou**
# Description
I had to add new functions in `node.go` to get the desired coverage. @libotony Please let me know what you think.

Fixes # ([issue](https://github.com/vechainfoundation/protocol-board-repo/issues/32))

## Type of change
Testing 

# How Has This Been Tested?
`make test-coverage`

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] New and existing E2E tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have not added any vulnerable dependencies to my code

### CODE REVIEW

**Comment by qianbin** [comment]
It'll be better to delay this PR, since the maindb-v4 brings a lot of changes to package `trie` and `muxdb`.

**Comment by nwbrettski** [comment]
@qianbin we can mark the `trie` and `muxdb` code coverage tasks as blocked until the `maindb-v4` is merged into `main`.

**Comment by qianbin** [comment]
> @qianbin we can mark the `trie` and `muxdb` code coverage tasks as blocked until the `maindb-v4` is merged into `main`.

OK, thanks.

**Comment by otherview** [comment]
@nwbrettski @libotony @qianbin 

I understand that there will be changes in `maindb-v4` that will change this PR. It does seem that this PRs goal (outside adding tests) is to improve code coverage, which it does.

Since the maindb-v4 is still under dev/test we should make a call to either merge this PR or remove it to avoid have stale PR's.

**Pull request closed without merging**
