### PR TITLE
V2 module

### PR DESCRIPTION
**Pull request by libotony**
Fixes the following issue:

``` bash
go get github.com/vechain/thor/thor@v2.1.0
go: github.com/vechain/thor/thor@v2.1.0: github.com/vechain/thor@v2.1.0: invalid version: module contains a go.mod file, so module path must match major version ("github.com/vechain/thor/v2")
```

And also the last version listed in https://pkg.go.dev/github.com/vechain/thor is still v1.7.4

Ref https://github.com/golang/go/issues/35732

### CODE REVIEW

**Comment by qianbin** [comment]
WTF, it's crazy.

**Comment by qianbin** [comment]
Have you tried `replace github.com/vechain/thor => ./` ?

**Comment by libotony** [comment]
> Have you tried `replace github.com/vechain/thor => ./` ?

You mean to keep all import path in the source to be `github.com/vechain/thor`? I don't know if this is a good practice in go.

**Comment by libotony** [comment]
I made a test locally, to use `replace github.com/vechain/thor => ./` you also need to declare you require `github.com/vechain/thor` so `github.com/vechain/thor v1.7.4` will be listed in the dependency. There is also a problem that you can not use v1's internal packages in `v2`.

```
package github.com/vechain/thor/v2/muxdb
        muxdb/muxdb.go:20:2: use of internal package github.com/vechain/thor/muxdb/internal/engine not allowed
```

**Comment by libotony** [comment]
Conflicts resolved, PTAL @qianbin

**Review by qianbin — APPROVED** [review]

**Pull request merged**
